package no.hiof.danirljr.modelviewtask.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFB60077)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD8E6)
val md_theme_light_onPrimaryContainer = Color(0xFF3D0025)
val md_theme_light_secondary = Color(0xFF8134C8)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF0DBFF)
val md_theme_light_onSecondaryContainer = Color(0xFF2C0050)
val md_theme_light_tertiary = Color(0xFF00677D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFB2EBFF)
val md_theme_light_onTertiaryContainer = Color(0xFF001F27)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF24005A)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF24005A)
val md_theme_light_surfaceVariant = Color(0xFFF1DEE3)
val md_theme_light_onSurfaceVariant = Color(0xFF504348)
val md_theme_light_outline = Color(0xFF827378)
val md_theme_light_inverseOnSurface = Color(0xFFF6EDFF)
val md_theme_light_inverseSurface = Color(0xFF3A1D71)
val md_theme_light_inversePrimary = Color(0xFFFFAFD2)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFB60077)
val md_theme_light_outlineVariant = Color(0xFFD4C2C7)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFAFD2)
val md_theme_dark_onPrimary = Color(0xFF63003E)
val md_theme_dark_primaryContainer = Color(0xFF8B005A)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD8E6)
val md_theme_dark_secondary = Color(0xFFDDB7FF)
val md_theme_dark_onSecondary = Color(0xFF490080)
val md_theme_dark_secondaryContainer = Color(0xFF680BAE)
val md_theme_dark_onSecondaryContainer = Color(0xFFF0DBFF)
val md_theme_dark_tertiary = Color(0xFF59D5F8)
val md_theme_dark_onTertiary = Color(0xFF003642)
val md_theme_dark_tertiaryContainer = Color(0xFF004E5F)
val md_theme_dark_onTertiaryContainer = Color(0xFFB2EBFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF24005A)
val md_theme_dark_onBackground = Color(0xFFEADDFF)
val md_theme_dark_surface = Color(0xFF24005A)
val md_theme_dark_onSurface = Color(0xFFEADDFF)
val md_theme_dark_surfaceVariant = Color(0xFF504348)
val md_theme_dark_onSurfaceVariant = Color(0xFFD4C2C7)
val md_theme_dark_outline = Color(0xFF9D8C92)
val md_theme_dark_inverseOnSurface = Color(0xFF24005A)
val md_theme_dark_inverseSurface = Color(0xFFEADDFF)
val md_theme_dark_inversePrimary = Color(0xFFB60077)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFAFD2)
val md_theme_dark_outlineVariant = Color(0xFF504348)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFB60077)
